GoogleCloudPlatform/kubectl-ai

README.md
main.go

Removed the "-" argument for reading content from STDIN. It makes `kubectl-ai` consistent with how unix commands handle `stdin`.
I was surprised how simple it was to add.

Added support for direct stdin support

---

k8s-bench/tasks/fix-service-routing/verify.sh

I saw a message saying that the --timeout flag on kubectl run is ignored,
so switching to use bash timeout instead.

fix: don't use kubectl run --timeout

---

k8s-bench/eval.go
k8s-bench/main.go

Ensure that k8sbench can log stdout/stderr to a file, so we can see what is going on.
I also moved setup.sh, as otherwise the second run for each scenario is (hopefully) already fixed by the first run. Ironically the LLM seems to do better when we do set up the scenario correctly each time.

k8sbench: log stdout/stderr to file

---

agent.go
main.go
pkg/llmstrategy/chatbased/chatbased_systemprompt_template_default.txt
pkg/llmstrategy/chatbased/strategy.go
pkg/llmstrategy/interfaces.go
pkg/llmstrategy/react/react_prompt_template_default.txt
pkg/llmstrategy/react/strategy.go

Highlights:
1. Prompts are now kept in separate text files and are read using `go:embed` directives.
2. Wired `PreviousQueries` all the way (I think we can make better use of these in both the strategies).
Did vibecheck using qwn-coder-2.5 model as well today and results have been promising so far.

embed the prompt templates using go:embed and minor fixes

---

gollm/factory.go

Starting with just the scheme e.g.
* LLM_CLIENT=vertexai://
* LLM_CLIENT=gemini://
* LLM_CLIENT=ollama://

gollm: add a simple scheme for env-var based LLM configuration

---

gollm/factory.go
gollm/gemini.go
gollm/interfaces.go
gollm/llamacpp.go
gollm/ollama.go
gollm/vertexai.go
main.go
mcp.go
pkg/agent/conversation.go

- main.go was too cluttered for my taste, so cleaned it up (always keep the entropy in check :))
- removed the support for updating the model in the interactive shell because it requires restarting the conversation and just wasn't worth the complexity.
- removed unnecessary model fetching. Fetch only when needed and cache it
- subcommands such as `version`, `models` now works for non-interactive session as well.

Cleaned up the code

---

main.go

The config directory on MacOS is not ~/.config and is somewhat surprising to me.
Add a multi-path loader and also try loading from ~/.config.

Better configuration loading

---

gollm/factory.go
gollm/gemini.go
gollm/interfaces.go
gollm/llamacpp.go
gollm/ollama.go
gollm/vertexai.go
pkg/agent/conversation.go

Realized I had a bug in the retry logic in the way we detect if error is retryable. 
There are more improvements I want to but will keep it for later PRs. For example (take the feedback from the API about backoff delay) and some minor improvements for other providers. Overall, this is working pretty nicely especially today got lots of 429 errors for `gemini-2.5-pro-experimental`.

Fixed bug in retrying logic

---

main.go

Two changes:
- use gemini-2.5-pro-experimental (Google's strongest AI model yet) as the default
- Use tool-calling by default because the default model supports tool use natively.

Use gemini-2.5-pro as default gemini model

---

k8s-bench/eval.go
main.go
pkg/agent/conversation.go
pkg/ui/interfaces.go
pkg/ui/terminal.go

Highlights:
1. `kubectl-ai` will now ask for permission to run `kubectl` commands that modifies resources in user's cluster. Users can override this behavior by using `--skip-permissions` command line flag.
2. Tweaked the confirmation flow to present users will the choice to 1) approve 2) approve and remember the choice for rest of session 3) decline. The option to approve and remember the choice makes the flow less annoying when user is comfortable with the modifying resources and trusts the tool/model more.
The run below shows the confirmation flow:
```sh
$ ./kubectl-ai "double the capacity of nginx application in hello namespace"
Okay, I can help with that. First, I need to find the deployment for the nginx
application in the 'hello' namespace and check its current size.
Running: …
```

Toggled ask-for-configuration defaults to confirm by default

---

k8s-bench/eval.go
k8s-bench/main.go
k8s-bench/pkg/model/results.go
main.go
pkg/agent/conversation.go
pkg/ui/blocks.go
pkg/ui/terminal.go

This is relevant when you invoke the agent with the query (or task description) on the command line, for ex. `kubectl-ai "bump up the capacity for nginx app"`. This will now drop the user in repl mode by default unless user specified `kubectl-ai --quiet` to disable non-interactive session. This is primarily motivated by my experience of using the tool. I wired the option all the way to `k8s-bench` as well and that helps if you are debugging any eval failure and having access to the repl with all the LLM chat context is useful.
- While using the agent command in a piped syntax or providing the input from stdin, it wasn't compatible with permission and interactive repl flow. Introduced configuration to use tty in those cases.
- Using `gemin-2.5-pro-preview-03-25` by default because it has …

Added Quiet mode

---

modelserving/images/llamacpp-server/Dockerfile

This fixes this error `CMake could not find CURL` when running `modelserving/dev/tasks/build-images`

Fix the error building modelserving images

---

gollm/factory.go

Before:
```sh
> go run . -llm-provider=azopenai -model gpt-4o-mini -quiet "show me all pods in the default namespace"  
creating llm client: provider "" not registered
exit status 1
```
After:
```sh
> go run . -llm-provider=azopenai -model gpt-4o-mini -quiet "show me all pods in the default namespace" 
Running: kubectl get pods -n default
Here are all the pods in the default namespace:                                 
NAME                                 READY   STATUS    RESTARTS      AGE      
hello-hello-world-64cfbbf7dc-t7fsf   1/1     Running   1 (79m ago)   4d14h    
The pod  hello-hello-world-64cfbbf7dc-t7fsf  is currently running and has been  
up                                                                              
for over 4 days. 🚀
```

Allow to specify the LLM provider ID instead of URL

---

k8s-bench/main.go
k8s-bench/tasks/create-network-policy/setup.sh
k8s-bench/tasks/create-network-policy/verify.sh
main.go

Two changes:
- Found out a bug that was causing this eval to fail for all the models.
- Revered to llm provider name without the scheme compatible

Fixed bug in create-network-policy eval

---

k8s-bench/go.mod
k8s-bench/go.sum

The k8s.io/klog/v2 package is not `indirect`. Also cleanup.

k8s-bench: Fix wrong `indirect` k8s.io/klog/v2 in the go.mod

---

README.md
k8s-bench.json
k8s-bench.md
k8s-bench/README.md
k8s-bench/main.go

Highlights:
- Updated the results for the three gemini models `2.5-pro-preview`, `2.5-pro-flash`, and `gemma3-27b`
- Analyze evals now accept an argument to ignore tool-use-shim because tool-use-shim is part of agent harness and isn't worth publishing for public consumption
- minor cleanups.

Updated k8s-bench results and minor cleanup

---

pkg/agent/conversation.go

Otherwise the KUBECONFIG variable won't be passed down to the kubectl call

fix: pass kubeconfig to tool execution

---

gollm/openai.go

If the user has chosen a model, it's probably because the user wanted to use it...

fix: don't dictate the name for the models

---

main.go

I noticed that the change of @mattn in this commit https://github.com/GoogleCloudPlatform/kubectl-ai/commit/5fd397b2cf153798f30209fff191258c48289433 did not take effect since there was another change on top of it. I raised this PR to fix it.

fix(tmp): correct overwritten tmp folder mentioned in (#132)

---

go.mod
main.go

cobra and viper don't play particularly nicely together by default.
Use the Options pattern that seems to work elsewhere.

refactor: avoid global variable with cobra/viper

---

README.md

$ is not part of the command, but a prompt indicator. It is better to avoid including the shell prompt symbol ($) so users can copy commands easily.
Tools like markdownlint support style rules such as [MD014 – Dollar signs used before commands without showing output](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md014), encouraging separation of prompt and command.

Omit dollar signs

---

README.md
install.sh

This update introduces a new `install.sh` script into the repository, enabling streamlined installation of the `kubectl-ai` CLI tool. The script automatically detects the user's OS and architecture, retrieves the latest release from GitHub, and installs the binary into `/usr/local/bin`. This simplifies the setup process, ensuring users can easily deploy the CLI tool with minimal manual steps.
- New `install.sh` script added to repository root.
- **OS Detection:** Supports Linux and macOS (Darwin).
- **Architecture Detection:** Supports amd64/x86_64 and arm64/aarch64.
- **Latest Release Fetch:** Uses the GitHub API to automatically identify the most recent release.
- **Installation Method:** Downloads the release tarball, extracts the binary, and installs it to `/usr/local/bin`, with …

feat(install): add quick and manual install options in README and script

---

modelserving/dev/tasks/run-local

This PR improves the robustness of the `run-local` script used for building and launching the local `llama-server`. It adds a safety check to ensure that the required `dev/tasks/build-images` script exists and is executable before attempting to run it.
- ✅ Added an existence and executability check:
```bash
[[ -x dev/tasks/build-images ]] || {
echo "build-images not found"; exit 1;
}
```
•	Prevents obscure failures in environments where the build script may be missing or not yet generated.
•	Makes the development workflow more predictable and user-friendly.
❓Why
Without this check, the script would fail with a less descriptive error if build-images is missing or lacks execution permission. This change provides an early and clear error message, improving developer experience.
No functional …

Chore: add existence check for build-images script

---

README.md

I'm trying to use remote ollama server as llm-provider. But there is no example to do that.
After few hours tracing the code, I found the answer: 
https://github.com/ollama/ollama/blob/0d6e35d3c67cf37de1c425d178c71d7351083013/envconfig/config.go#L17
[`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R58-R60): Added a note on how to use the `OLLAMA_HOST` variable to specify the host of a remote `ollama` server. the documentation, add OLLAMA_HOST into example.

Doc enhancement: Add OLLAMA_HOST into example

---

pkg/ui/observable.go

The variable s is defined again inside the for-loop, which causes the external variable s to be hidden, which in turn causes the for-loop to be handled incorrectly.

fix Observable#AddSubscription on s is shadowed

---

mcp.go
pkg/tools/bash_tool.go
pkg/tools/kubectl_tool.go
pkg/tools/tools.go
pkg/tools/trivy_tool.go

- Replaced string keys with a custom contextKey type for kubeconfig and work_dir
- Prevents context key collisions and follows Go best practices
- Resolves static analysis/linter warnings
- No functional changes
Closes #174

refactor(tools): use typed context keys for kubeconfig and work_dir

---

cmd/main.go
pkg/agent/conversation.go
pkg/ui/blocks.go

Returning the object pointer from a set accessor might not be the most expected method signature.

refactor: simplify AgentTextBlock methods and improve message handling

---

README.md

It's a pretty common use case for OSS to have badges, they are convenient and make the repository be more _appealing_ if you could say so:
- `shields.io` uses [Creative Commons Zero](https://github.com/badges/shields/blob/master/LICENSE) License 
- `goreportcard` uses [Apache 2.0](https://github.com/gojp/goreportcard/blob/master/LICENSE) License.

Feature: add shields in README

---

cmd/main.go
gollm/azopenai.go
gollm/factory.go
gollm/gemini.go
gollm/grok.go
gollm/llamacpp.go
gollm/ollama.go
gollm/openai.go

- Add support for skipping SSL certificate verification via a new SkipVerifySSL flag, CLI option, and environment variable
- Refactor client factory functions to accept a unified ClientOptions struct, enabling custom configuration such as SkipVerifySSL
- Implement createCustomHTTPClient utility to provide HTTP clients with optional SSL verification
- Update provider client constructors (OpenAI, Azure OpenAI, Grok, LlamaCpp, Ollama) to support custom HTTP clients and SkipVerifySSL
- Improve error handling and variable declarations for clarity and consistency
- Minor code cleanup and reorganization for maintainability
fixed https://github.com/GoogleCloudPlatform/kubectl-ai/issues/211
cc @droot

feat: add configurable SSL verification and refactor client options

---

cmd/main.go
pkg/agent/conversation.go

Close #204 
Add `--additional-prompt-template-file-paths` flag with templates that are appended to the default prompt file when generating the prompt.

Add support for additional prompt template files

---

dev/ci/presubmits/verify-autogen.sh
dev/ci/presubmits/verify-format.sh
dev/ci/presubmits/verify-gomod.sh
dev/tasks/generate-github-actions.sh
pkg/ui/terminal.go

Two separate but slightly related changes (captured in separate commits)
Initialize these readers only when needed. Two benefits:
1. We won't setup these when running in non-interactive mode (`--quiet`)
2. k8s-bench feeds the interactive script on stdin, that forces the kubectl-ai to use tty for input when the input is through stdin. And github actions don't make /dev/tty available and that causes `k8s-bench` to fail when running in CI (github actions)
CI changes
1. Added step to run lightweight evals (two tasks related to scaling)
2. Added a workflow for periodic evaluation
Note: I am using keyless setup for authenticating github actions with GCP's vertexai platform. I expect a few bumps. I have tested this in my own fork, but let see how it goes here. 
*UPDATE*: Had to remove the …

Lazy initialization of input readers and evals

---

pkg/tools/bash_tool.go
pkg/tools/kubectl_tool.go

Fixes #228
Find the bash executable using `exec.LookPath` instead of hardcoding `/bin/bash`. Falls back to `/bin/bash` if not found in PATH. Improves compatibility on systems where bash might be installed in a non-standard location.
On some systems (e.g. NixOS), executables might not be in standard locations like /bin/bash.

fix(tools): Use exec.LookPath to find bash executable before running bash commands

---

cmd/main.go
pkg/tools/custom_tool.go
pkg/tools/tools.go

Fixes https://github.com/GoogleCloudPlatform/kubectl-ai/issues/222
Usage: `kubectl-ai --custom-tools-config=<path to tools config>` (default location `~/.config/kubectl-ai/tools.yaml`)
Example tool config (this takes multiple custom tools):
```yaml
- name: nomos_status
description: "Runs the 'nomos status' command to check Config Sync status on specified Kubernetes clusters."
command: "nomos status"
command_desc: "The nomos status command for Config Sync status on the cluster"
```
(Tool description gives LLM hint when to use the tool; command description is more about syntax and examples of command usage.)
Example result:
Note that `kubectl-ai` can still answer questions without the tool. Adding custom tools enriches the answer.

Support custom tools

---

.github/workflows/ci-periodic.yaml

This pull request makes a small change to the `.github/workflows/ci-periodic.yaml` file by adding a condition to the `run-eval` job. The job will now only run if the repository is `GoogleCloudPlatform/kubectl-ai`.

fix(ci): Ensure job runs only for the correct repository

---

gollm/openai.go

- Update OpenAI client factory to accept and use ClientOptions
- Add support for passing a custom HTTP client, enabling options like skipping SSL verification
- Refactor NewOpenAIClient to take ClientOptions as a parameter

feat: refactor OpenAI client to support customizable connection options

---

pkg/tools/custom_tool.go

This allows skipping confirmation for read-only tools, e.g. 
```shell
> kubectl-ai
Hey there, what can I help you with today?                                  
>>> What's the status of my Config Sync?                                                                                                             
Running: nomos_status(modifies_resource=no)
```

Add modifies_resource parameter to custom tool

---

.github/actions/kind-cluster-setup/action.yaml
.github/workflows/ci-periodic.yaml
.github/workflows/k8s-bench-evals.yaml

This update introduces a new GitHub workflow (`k8s-bench-evals.yaml`) designed to facilitate self-service, on-demand execution of Kubernetes benchmark evaluations. It provides manual trigger capabilities, allowing PR owners or developers to test specific evaluation tasks before merging, thereby ensuring robustness and correctness of new or modified evaluations.
- Workflow configuration (`.github/workflows/k8s-bench-evals.yaml`)
- Custom actions for setting up Kind clusters (`.github/actions/kind-cluster-setup`)
- Evaluation scripts (`run-evals.sh` and `analyze-evals.sh`)
- Workflow is triggered manually via `workflow_dispatch`.
- Allows user input for `task_pattern`, enabling targeted testing of specific evaluation tasks.
- Uses a custom setup action for creating a Kind Kubernetes …

ci: add workflow for k8s-bench evaluations on push/PR

---

pkg/agent/conversation.go

Closes #144 , if a user declines a tool operation during (selects "3" in the confirmation prompt),https://github.com/GoogleCloudPlatform/kubectl-ai/blob/a5ea5cbb413e5d3dfaf1c80ac68ebe1fdcfd3261/pkg/agent/conversation.go#L261-L265
This causes OpenAI-compatible providers to error, as their protocol requires a tool message for every tool_call during streaming requests, even if the operation is skipped.
- **On user decline (option "3") for a tool call:**
- The agent now appends a tool message (`gollm.FunctionCallResult`) with `status: "declined"` and an error message to `currChatContent`.
- We append `call.ID & call.Name` to comply with openai's api
- **Result:**  
- The LLM is always informed of the user's decision, and the protocol requirement for tool message responses is met, even when …

FIX | Stop Agentic Loop and Await User Input When Tool Call is Declined

---

pkg/agent/systemprompt_template_default.txt

Removed the conditional block (`if .EnableToolUseShim`) and its associated instructions, simplifying the template and ensuring the prompt is more concise.

cleanup: deduplicate common instruction logic in `systemprompt_template_default.txt`

---

pkg/agent/conversation.go
pkg/ui/terminal.go

This PR enhances https://github.com/GoogleCloudPlatform/kubectl-ai/issues/275 & improves the user experience of confirmation prompts in the CLI by:
- Making the prompt more intuitive and informative
- Supporting natural language inputs like "yes", "no", "y", and "n" in addition to numeric options
Here are some screenshot's -

fix: Improve CLI prompt and input handling for confirmation choices

---

cmd/main.go

Fix: #280
After the https://github.com/GoogleCloudPlatform/kubectl-ai/pull/271  change,
If there is no `config.yaml` file in the environment, kubectl-ai will fail to run.
```
root@gpu3090:~/oss/kubectl-ai# task run
task: [run] go run ./cmd
failed to load config file: could not load config from "/root/.config/kubectl-ai/config.yaml": open /root/.config/kubectl-ai/config.yaml: no such file or directory
exit status 1
task: Failed to run task "run": exit status 1
```
This behavior is unexpected, so we should revert this part of the code to its previous state,
making it ​​ignore missing config files​​ (i.e., treat them as ​​optional​​).
----
kubectl-ai version: main branch

Fix: make config.yaml Optional 

---

pkg/agent/conversation.go
pkg/tools/bash_tool.go
pkg/tools/custom_tool.go
pkg/tools/interfaces.go
pkg/tools/kubectl_tool.go
pkg/tools/tools.go
pkg/tools/trivy_tool.go

Implements a simple timeout-based approach for handling streaming kubectl commands. It addresses issues with commands like `kubectl logs -f` and `kubectl get -w` by automatically terminating them after 7 seconds, while still allowing users to see the output in real-time.
- Added detection for various streaming kubectl commands:
- `kubectl logs -f`
- `kubectl get -w`
- `kubectl attach`
- Explicitly blocked interactive commands:
- `kubectl exec -it`
- `kubectl port-forward`
- Implemented a 7-second timeout for all streaming commands
- Added proper stream type identification for different operations
- Simplified the command execution logic by removing complex input handling
```
>>> ^C
❯ ./kubectl-ai --llm-provider=openai --model=claude-3-5-sonnet-20241022 "create a pod in the default …
```

FIX: kubectl streaming and interaction bashtool #122 #232

---

cmd/main.go

Reverts GoogleCloudPlatform/kubectl-ai#277
We discovered our periodic evals were failing.
```sh
KUBECONFIG=~/.kube/auto-ai-1 TEST_ARGS="--enable-tool-use-shim=false --models gemini-2.5-flash-preview-04-17 --task-pattern scale-down" ./dev/ci/periodics/run-evals.sh
...
...
Auto-configuring concurrency to 1 (number of tasks)
Running tasks with concurrency: 1
Worker 0: Evaluating task: scale-down-deployment
Running command: /usr/local/google/home/sunilarora/work/kubectl-ai/k8s-bench/tasks/scale-down-deployment/setup.sh
namespace/scale-down-test created
Warning: autopilot-default-resources-mutator:Autopilot updated Deployment scale-down-test/web-service: defaulted unspecified 'cpu' resource for containers [nginx] (see http://g.co/gke/autopilot-defaults).
deployment.apps/web-service created …
```

Revert "fix: improve stdin data detection logic in debug mode"

---

pkg/agent/conversation.go

Proposed fix for issue in #296.
At the end of the given error message, we see:
`Here are a few examples from the logs:\\n": unexpected end of JSON input`
suggesting there should be some examples printed after this.
I found the easiest way to recreate this was to just ask about logs and try to get it to copy/paste a section for the user to view. This only happens with --enable-tool-use-shim flag, because candidateToShimCandidate() is guarded behind a check for this flag.
With some investigating, I found the program trying to embed a multi-line string in its output, delimited by ` ``` `. extractJSON() will return saying that valid JSON is found when it finds ` ```json ` opener and ` ``` ` closer. In candidateToShimCandidate(), as it iterates through the stream, it will find the start of the …
```

Fix error when trying to include multi-line string in conversation output when using --enable-tool-use-shim

---

k8s-bench/eval.go
k8s-bench/go.mod

Currently including `expect` line in an eval's task.yaml won't actually run these checks, since the `journal.ActionUIRender` got obsoleted somewhere in the past. This means that running an eval now that *only* relies on the expect block like #295, will always succeed as long as there are no other errors during the run.
This fix saves a copy of stdout from running the eval, parses for the final llm response, and checks if it contains the expected text.
Another option could be to stick with the journal checking, and any time we write to sdout include a journal entry, like https://github.com/GoogleCloudPlatform/kubectl-ai/blob/4d4005ae9c1831ccb61b1d27bf86a68b1917fc5a/pkg/agent/conversation.go#L190, but I decided against it since it seems like a higher-maintenance option.

Change eval's expect block to parse stdout

---

k8s-bench/tasks/create-simple-rbac/cleanup.sh
k8s-bench/tasks/create-simple-rbac/setup.sh
k8s-bench/tasks/create-simple-rbac/task.yaml
k8s-bench/tasks/create-simple-rbac/verify.sh

Adds create-simple-rbac eval. The goal of this eval is to cover the case of the agent creating a pods read-only RBAC setup for an existing service account.
-verify checks for expected and denied permissions

eval: add create-simple-rbac eval

---

cmd/main.go
pkg/agent/conversation.go
pkg/tools/tools.go

This lets us run kubectl from a temporary directory, even if the
--kubeconfig flag is set to a relative path in the current directory.
Issue #340

resolve kubeconfig flag to absolute path

---

cmd/main.go

This is useful for debugging, and is less disruptive in HTML mode.

Expose the --alsologtostderr flag

---

pkg/mcp/client.go
pkg/tools/mcp_tool.go

I don't think we should be mangling the arguments,
once we pass the schema the LLM seems to do a reasonable job.

mcp client: don't mangle arguments

---

pkg/ui/terminal.go

With the default fixed width of 80 (in the glamour library), I find a lot of my screen real estate getting wasted and a lot of scrolling needed when I run kubectl-ai on my terminal, so I wanted to tackle this.
There are few different paths to tackle this and honestly I am bit dicey about the path I took but here is my thinking:
1. I didn't want to figure the terminal width using one of the standard ways (`term.GetSize` or `COLUMNS` env var) since then the change would affect most of the folks by default.
2. I didn't want to add a new `--width` flag just for this.
3. I went with a totally custom env var approach so that only folks who really want this can use it.
I am open to thoughts and folks preferring some other path over this path, LMK.

Allow making width configurable for kubectl-ai's terminal UI

---

go.mod
pkg/ui/terminal.go

Adds support for `KUBECTL_AI_TERM_WIDTH=auto` as outlined here: #396

add auto support

---

k8s-bench/eval.go
k8s-bench/main.go
k8s-bench/tasks/setup-dev-cluster/setup-dev-cluster.md
k8s-bench/tasks/setup-dev-cluster/task.yaml

This PR adds the ability to store task prompts in external files instead of embedding them directly in YAML configurations.
- Added `PromptFile` field to `ScriptStep` struct
- Implemented `ResolvePrompt()` method to load prompts from files or inline content
- Refactored `setup-dev-cluster` task to use external `setup-dev-cluster.md` file
- Maintains full backward compatibility with existing inline prompts
- Cleaner YAML configurations
- Better maintainability for complex prompts
- Improved editing experience with markdown files
- Supports both absolute and relative file paths

feat: modularize prompt resolution with new `promptFile`

---

k8s-bench/eval.go
k8s-bench/tasks/create-pod/task.yaml

In order to fix the flakiness in #392 we need to support checking against multiple outputs which can be accomplished through regex. This change also results in eval behavior changing when both verify and expect are specified, the result will be the logical OR between them.

Change task expectations to use regexp

---

README.md

Updated YAML configuration examples in `README.md` to use correct camelCase field names (e.g., `llmProvider` instead of `llm-provider`) to match the JSON tags in the `Options` struct.
resolves https://github.com/GoogleCloudPlatform/kubectl-ai/issues/407

Update README.md to fix configuration options

---

gollm/gemini.go

Noticed while doing some of the containerization that some of the errors from the vertex-ai client would not be surfaced, such as credentials being missing:
Before: 
After:

feat: surface error messages from vertex-ai-client

---

pkg/agent/conversation.go

Previously, the agent registered function definitions with the LLM before initializing the MCP client. This resulted in only the built-in tools being passed to the model, leaving it unaware of any external tools available through MCP

fix: make llm aware of mcp tools

---

pkg/agent/conversation.go

Surface MCP tool call errors to the UI 
Before:
After:

fix: surface error from mcp tool calls

---

pkg/agent/systemprompt_template_default.txt

Modifies system prompt to fix #447. If anyone has better ways of evaluating if this works 100 percent of the time please let me know!

fix: vertexai dropping kubectl

---

cmd/main.go
pkg/ui/terminal.go

We recently added feature to show tool output (with truncation limit) by default. After a testing it out today, I am realizing that the terminal output is getting even more verbose and also causing duplication of information.
This PR restores the original behavior of not showing the tool output by default. Instead, now users can use `--show-tool-ouput` command line flag to always display the tool output. 
default behavior:
opt-in behavior:
/cc @noahlwest  @ShubyM 
Also adjusted the "Running" to align with other outputs.

feat: Added --show-tool-output to display tool's output

---

.gitignore

I have been using `air` to rebuild/reload and found it useful especially while iterating on the web interface. Adding the air toml to gitignore.

chore: ignore .air.toml

---

README.md

This fixes the reference var in the main README for ui config type.
To add to this: I found in code that there is a TUI type too, but as it is not working as it should (tested on Mac and for every input you get a weird string in the user input box) I haven't advertised it in the README.

Fix Var reference for UI configuration for ui Type

---

cmd/main.go
pkg/agent/conversation.go

Adds "resume-session <session ID>" to metaquery handling.
demo (start from no session, load one session, load another session): https://github.com/user-attachments/assets/8ceca555-ab60-482a-8d81-e75074c437ab
demo (changing sessions in web ui): https://github.com/user-attachments/assets/49c4dd48-d13e-43e6-835f-c19d1421c9cf

feat: Add resume-session to metaquery handling

---

k8s-bench/tasks/create-canary-deployment/artifacts/deployment-v1.yaml
k8s-bench/tasks/create-canary-deployment/artifacts/service.yaml
k8s-bench/tasks/create-canary-deployment/cleanup.sh
k8s-bench/tasks/create-canary-deployment/setup.sh
k8s-bench/tasks/create-canary-deployment/task.yaml
k8s-bench/tasks/create-canary-deployment/verify.sh

Adds an eval for creating a canary deployment with some stated requirements.
* This eval fails 80% or more of the time on Gemini 2.5 pro, due to small mistakes in correctness. Wrong deployment names, incorrect number of replicas, scaling down the stable deployment even though explicitly told not to. The overall task is relatively simple but since these small measure of correctness are important, and even gemini 2.5 pro keeps making mistakes on them, I'm marking it as hard.
Generated using the prompt in #471 with this added input:
```
Prompt: "We want to test a new version of our recommendation engine (image tag v1.29) in production. Can you deploy it as a canary? We want about 10% of traffic to go to the new version. The current deployment is named engine-v2-0 and has 10 replicas." …
```

eval: Add canary deployment eval

---

cmd/main.go
pkg/agent/conversation.go
pkg/ui/terminal.go

Lets people start without a persisted session and switch at any time with save-session
Also, adds a check on ctrl+c exit whether user wants to save the current in-memory session.
demo (shows use of save-session, yes on exit save, and no on exit save): https://github.com/user-attachments/assets/dccb62e9-3f48-4b7d-b897-ac1ea6cb23ba

feat: Add save-session metaquery and ask to save on exit

---

pkg/ui/terminal.go

This is reverting part of the functionality of this PR https://github.com/GoogleCloudPlatform/kubectl-ai/pull/484 where we ask users to save session on exiting.
I tried the new UX and there are rough edges around exiting when users selects to not save the session. Current UX seems to give impression that the agent is working on it but does nothing. The issue is from the original UX not the new session saving UX. We can introduce it when when we fix the exiting UX overall. 
For now, only keeping the `save-session` meta query handling support.

do not ask uses to save session on exit

---

README.md

Added DeepWiki bagge to the kubectl-ai project by modifying the Readme.md file

Adding DeepWiki badge to Github page

---

install.sh

- Allow the installation directory to be customized using the INSTALL_DIR environment variable
- Update installation message to reflect the configurable target directory
1. Make sure you have write permission to $INSTALL_DIR, or use sudo if necessary.
2. If $INSTALL_DIR does not exist, the install command will attempt to create it, but this may require elevated privileges.
3. If installing to a directory not in $PATH, you must reference the full path to use the binary or add it to your $PATH manually.

feat: make installation directory configurable via INSTALL_DIR env var

---

k8s-bench/tasks/list-images-for-pods/artifacts/Makefile
k8s-bench/tasks/list-images-for-pods/artifacts/manifest.yaml
k8s-bench/tasks/list-images-for-pods/task.yaml
k8s-bench/tasks/list-images-for-pods/verify.sh
k8s-bench/tasks/statefulset-lifecycle/task.yaml
k8s-bench/tasks/statefulset-lifecycle/verify.sh

These two evals were failing consistently during my k8s-bench runs.
`statefulset-lifecycle` eval was relying on llm to guess things we verified, like the test file and its contents. I made the prompt and verification more specific so the llm can follow instructions instead of getting a lucky guess.
`list-images-for-pods` would time out every single time I tried to run it on a KinD cluster (my preferred cluster type for running evals). I pretty much just threw this problem at gemini, it suggested there was an issue with the given version of mysql running on local environments like kind or docker desktop, and suggested this older version as a fix. I updated the Makefile and rebuilt the manifest, and the eval no longer timed out on KinD or GKE clusters. Also removed unnecessary verify.sh for …

fix: address statefulset-lifecycle and list-images-for-pods consistent failures

---

k8s-bench/tasks/multi-container-pod-communication/task.yaml
k8s-bench/tasks/multi-container-pod-communication/verify.sh

This eval relied on the LLM to make multiple correct guesses, else it would fail. 
I've made the prompt more explicit about what we want, also did a slight refactor to bring this eval closer to our best practices.
Example of a successful run on gemini:
```
Running verifier for task multi-container-pod-communication
Running command: .../kubectl-ai/k8s-bench/tasks/multi-container-pod-communication/verify.sh
Waiting for pod 'communication-pod' to be ready...
pod/communication-pod condition met
Pod is ready. Verifying configuration...
Testing web server access...
Verifying logger container can access nginx logs...
-rw-r--r--    1 root     root           185 Sep  9 19:23 /var/log/nginx/access.log
All verification checks passed!
Running command: …
```

fix: make multi-container-pod-communication eval less flaky

---

pkg/agent/conversation.go
pkg/tools/kubectl_filter.go

Two big changes related to command approval flow.
- Do not rely on LLM to determine if a command modifies resource or not.
- If LLM suggests a composite command such as `kubectl get pods | wc -l` or generic bash script command multiple commands, we will always ask for approval even if the kubectl commands are readonly (this is to avoid exfilteration attacks).
We are seeing requests for using the tool against production clusters and without the above changes, I see a serious risk of prompt injection attacks.
It may appear that the above changes may cause `prompt fatigue` because it will ask the user to approve commands but majority of the use-cases involves read-only kubectl commands and our current static filter will cover those pretty well and not request user to approve those commands. …

feat: always ask for approval for non-readonly commands

---

dev/ci/periodics/analyze-evals.sh
k8s-bench/eval.go
k8s-bench/main.go
makefile

This change adds the last 20 lines for any eval failure to the failure message, and shows it in the generated markdown file from `k8s-bench analyze` if you include the `--show-failures flag`.
Usable with ./k8s-bench analyze (other args) --show-failures
Also usable with the make target, so we can run `make analyze-evals ARGS=--show-failures`
An example of what will show up in the generated markdown file:
```markdown
| Task | Provider | Result |
|------|----------|--------|
| create-canary-deployment | openai | ❌ fail |
**openai/gpt-oss-20b Summary**
- Total: 1
- Success: 0 (0%)
- Fail: 1 (100%)
**openai/gpt-oss-20b Failure Details**
**Task: create-canary-deployment**
verifier script failed: running command ~/kubectl-ai/k8s-bench/tasks/create-canary-deployment/verify.sh: exit status 1 …
```

feat: Add --show-failures flag to `analyze-evals`, update scripts

---

pkg/agent/conversation.go

We noticed that sometimes LLM respond with empty text even when no tool call is being made. This results in `kubectl-ai` to hang because terminal UI (or other UIs) will get blocked on reading from the agent's output channel.
This PR ensures that we let the users know in case LLM responded with no text and it also avoids UIs blocking on the output channel.

fix: handle empty LLM response

---

gollm/factory.go
pkg/agent/conversation.go

* adds timeout to http client (the default is 0 - no timeout)
* adds llm request and response tracing to the trace file, this is helpful for debugging
Example tracefile:
```yaml
action: llm.request
payload:
- Create a read-only role for pods bound to my reader-sa service account in the create-simple-rbac
namespace.
timestamp: "2025-09-30T11:27:13.49796764-07:00"
---
action: llm.response
payload:
raw:
candidates:
- content:
parts:
- functionCall:
args:
command: kubectl get namespace create-simple-rbac
modifies_resource: "no"
name: kubectl
thoughtSignature: CiQ... (cut for length)
role: model
finishReason: STOP
modelVersion: gemini-2.5-flash
usageMetadata:
candidatesTokenCount: 27
promptTokenCount: 1986
promptTokensDetails:
- modality: TEXT
tokenCount: 1986
thoughtsTokenCount: 157 …
```

feat: add llm request/response tracing, http client timeout

---

k8s-bench/eval.go
k8s-bench/main.go

* adds --create-kind-cluster flag to k8s-bench, which will create a new kind cluster for the invoked run, and delete it at the end
In testing, I noticed rarely that the kind cluster control plane can fail to come up and will close the program.

feat: Add ability to create new kind cluster for k8s-bench run

---

k8s-bench/tasks/horizontal-pod-autoscaler/verify.sh

The task assumes hpa name to be fixed and that is not stable so instead changed the logic to pick hpa from the target namespace.

fix: improve the logic for looking up hpa resource

---

CONTAINER.md

- Update section headings to use consistent Markdown formatting
- Improve readability by adding newlines and splitting long lines
- Enhance instructions for running Docker container with clearer command examples and multiline formatting
- Correct typo in the alternative terminal UI section header

docs: standardize and clarify Markdown documentation formatting

---

k8s-bench/eval.go
k8s-bench/main.go

Adds default 5 minute timeout to any task. Per-task timeout can also be set in the task.yaml

evals: Add per-task timeout to k8s-bench
