.gitignore, dev/ci/periodics/run-evals, k8s-bench/eval.go, k8s-bench/go.mod, k8s-bench/go.sum, k8s-bench/main.go, k8s-bench/pkg/model/results.go
- **eval: create helper script to run evals**
- **k8sbench: switch to sigs.k8s.io/yaml**
- **k8s-bench: start to write structured results**
=> k8s-bench: start to write structured results

agent.go
Remarkably, these don't seem to actually confuse the LLM!
=> Fix typo in prompt

gollm/gemini.go, gollm/interfaces.go, gollm/schema.go, gollm/vertexai.go
This is handy when we want structured output.
=> gollm: support restricting output to a response schema

agent.go, dev/tasks/format, gollm/persist.go, gollm/schema.go, k8s-bench/eval.go, k8s-bench/main.go, k8s-bench/pkg/model/results.go, pkg/journal/recorder.go, pkg/ui/interfaces.go, pkg/ui/terminal.go, tools.go
- **chore: task to apply license headers**
- **chore: add license headers to files**
=> chore: add license headers

agent.go, gollm/gemini.go, main.go, pkg/journal/log.go, pkg/llmstrategy/interfaces.go, tools.go
We want to compare multiple LLM strategies.
Start by refactoring in the same package, we will then rename.
=> Refactor: start to split out strategy

k8s-bench/eval.go, k8s-bench/main.go, k8s-bench/pkg/model/results.go, main.go
Add support for strategy flag to our eval harness
=> Able to eval strategies

main.go
Introduced during rebases (likely) before we had CI
=> chore: fix compilation error

agent.go, gollm/gemini.go, gollm/interfaces.go, gollm/vertexai.go, main.go
Minor fixes:
- duplicate flag (`model`) was causing panic
- updating the model during interactive session wasn't working
- minor cleanup
=> bugfix: update the model during the interactive session

gollm/gemini.go, gollm/ollama.go, gollm/persist.go, gollm/vertexai.go, k8s-bench/eval.go, pkg/llmstrategy/chatbased/strategy.go
- **k8sbench: record structured log also**
- **Record structured log in chat mode**
=> More structured logging

pkg/llmstrategy/react/strategy.go
1.   LLM prompt for the ReAct agent is significantly improved to steer LLM to return json output with json code block.
2.  Fixed a few bugs related to how we record history and present it to the LLM.
Have performed quick vibe check with ollama using `gemma2`, `mistral`, `llama3.1` and early results are very promising.
Here is a chat session using `gemma2` model driving the agent:
```shell
./kubectl-ai --llm-provider ollama --model gemma2 --strategy react
Hey there, what can I help you with today?
>> list pods in hello namespace
Running: kubectl get pods -n hello
kubectl is the primary tool for interacting with Kubernetes clusters and listing
pods by namespace is a common operation.
Here are the pods in the 'hello' namespace:
NAME                     READY   STATUS    RESTARTS   AGE …
```
=> react prompt improvements for emitting json codeblock

k8s-bench/tasks/create-network-policy/cleanup.sh, k8s-bench/tasks/create-network-policy/setup.sh, k8s-bench/tasks/create-network-policy/task.yaml, k8s-bench/tasks/create-network-policy/verify.sh, k8s-bench/tasks/create-pod-mount-configmaps/cleanup.sh, k8s-bench/tasks/create-pod-mount-configmaps/setup.sh, k8s-bench/tasks/create-pod-mount-configmaps/task.yaml, k8s-bench/tasks/create-pod-mount-configmaps/verify.sh, k8s-bench/tasks/create-pod-resources-limits/cleanup.sh, k8s-bench/tasks/create-pod-resources-limits/setup.sh, k8s-bench/tasks/create-pod-resources-limits/task.yaml, k8s-bench/tasks/create-pod-resources-limits/verify.sh, pkg/llmstrategy/react/react_prompt_template_default.txt
Some more evals for creating resources.
=> evals: added create resources evals (pod and networkpolicy)

dev/ci/periodics/run-evals, k8s-bench.md, k8s-bench/README.md, k8s-bench/eval.go, k8s-bench/main.go, k8s-bench/tasks/create-pod-resources-limits/task.yaml, k8s-bench/tasks/create-pod-resources-limits/verify.sh
Here is the eval report produced:
| Model | chat-based Success | chat-based Fail | react Success | react Fail |
|-------|------------|-----------|------------|-----------|
| gemini-2.0-flash | 7 | 3 | 8 | 2 |
| gemini-2.0-flash-thinking-exp-01-21 | 0 | 0 | 7 | 3 |
| gemma-3-27b-it | 0 | 0 | 8 | 2 |
| **Total** | 7 | 3 | 23 | 7 |
- Total: 40
- Success: 30 (75%)
- Fail: 10 (25%)
| Task | Provider | Model | Result | Error |
|------|----------|-------|--------|-------|
| configure-ingress | gemini | gemini-2.0-flash | ✅ success |  |
| create-network-policy | gemini | gemini-2.0-flash | ❌ fail |  |
| create-pod | gemini | gemini-2.0-flash | ✅ success |  |
| create-pod-mount-configmaps | gemini | gemini-2.0-flash | ✅ success |  |
| create-pod-resources-limits | gemini | gemini-2.0-flash | ✅ …
=> Added analyze subcommand to k8s-bench to generate eval report

main.go
We assume a yaml configuration and merge it in.
=> Basic configuration in ~/.config/kubectl-ai/config.yaml

k8s-bench/eval.go, k8s-bench/main.go, k8s-bench/tasks/configure-ingress/task.yaml, k8s-bench/tasks/create-network-policy/task.yaml, k8s-bench/tasks/create-pod-mount-configmaps/task.yaml, k8s-bench/tasks/create-pod-resources-limits/task.yaml, k8s-bench/tasks/create-pod/task.yaml, k8s-bench/tasks/fix-crashloop/task.yaml, k8s-bench/tasks/fix-image-pull/task.yaml, k8s-bench/tasks/fix-service-routing/task.yaml, k8s-bench/tasks/list-images-for-pods/task.yaml, k8s-bench/tasks/scale-deployment/task.yaml, k8s-bench/tasks/scale-down-deployment/task.yaml
- **k8s-bench: change syntax to support multiple-step interactions**
- **k8s-bench: start to support multi-step eval**
=> Start to support multi-step conversations

k8s-bench/eval.go, k8s-bench/main.go
- **k8s-bench: change syntax to support multiple-step interactions**
- **k8s-bench: start to support multi-step eval**
- **k8s-bench: allow running each task in its own cluster, easily**
=> Support cluster isolation

dev/ci/periodics/analyze-evals, k8s-bench.json, k8s-bench.md, k8s-bench/main.go, k8s-bench/tasks/list-images-for-pods/setup.sh, pkg/agent/systemprompt_template_default.txt
Ran following evals and updated the results:
- gemini-2.0-flash (tool-use shim-enabled/shim-disabled)
- gemini-2.0-flash-thinking-exp-01-21 (tool-use shim enabled)
- gemma-3-27b-it (w/ gemini, tool-use-shim-enabled)
- gemma3:12b (w/ ollama, tool-use-shim-enabled)
=> Updated k8s-bench results

main.go, pkg/agent/conversation.go, pkg/ui/blocks.go, pkg/ui/interfaces.go, pkg/ui/model.go, pkg/ui/observable.go, pkg/ui/terminal.go
Rather than have the LLM render directly to the screen,
it now renders to a document which is rendered to the screen.
This will enable features like streaming / reconnecting etc.
=> Document model in UI, to support streaming

gollm/factory.go, gollm/gemini.go, gollm/interfaces.go, gollm/llamacpp.go, gollm/ollama.go, gollm/shims.go, pkg/agent/conversation.go, pkg/ui/model.go, pkg/ui/terminal.go
Only implemented for the gemini/vertex client currently.
Also improve concurrency in the document model
=> Streaming support

gollm/factory.go, gollm/gemini.go, gollm/interfaces.go, gollm/llamacpp.go, gollm/ollama.go, gollm/shims.go, pkg/agent/conversation.go, pkg/ui/blocks.go, pkg/ui/model.go, pkg/ui/terminal.go
- **Minimal streaming support**
Also improve concurrency in the document model
- **Reintroduce markdown support with streaming**
=> Reintroduce markdown with streaming support

gollm/gemini.go
These are both required, so default the project from gcloud.
We use a hard-coded default of us-central1 for location.
This restores the previous behaviour.
=> gollm: default project and location for vertexai

main.go
This is to suppress harmless warning coming from the `genai` library to be printed on stdout/stderr by default. The warning exists because llm response contains text and non-text candidates and `genai` library wants us to be aware of that. Here is a sample run:
```sh
$ kubectl-ai "list nginx pods"
2025/04/17 09:21:53 Warning: there are non-text parts FunctionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from mod
el.
Okay, ....
Running: kubectl get pods -l app=nginx
2025/04/17 09:22:02 Warning: there are non-text parts FunctionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from mod
el.
Hmm, .....
Running: kubectl get pods -l app=nginx …
```
=> Redirect standard log to klog

gollm/gemini.go
Recognize the following env vars for vertexai:
* project: GOOGLE_CLOUD_PROJECT
* location: GOOGLE_CLOUD_LOCATION, GOOGLE_CLOUD_REGION
=> gollm: recognize well-known env vars

gollm/gemini.go
Even though these share a common client SDK, that is an implementation
detail that gollm should not (obviously) export through the public API.
Also move vertexai defaulting "down",
so that we get it even with NewVertexAIClient,
not just if we use the "URI" constructor.
=> gollm: make it easier to build vertex client

.github/workflows/ci-presubmit.yaml, dev/ci/presubmits/verify-gomod, dev/tasks/gomod
=> ci: add test for go.mod

main.go
=> use os.TempDir()

pkg/agent/systemprompt_template_default.txt
there was a typo in emojis in the systemprompt.
=> fixed the use of emojis in systemprompt_template

README.md
=> doc: add openai compatible llm api usage

pkg/tools/bash_tool.go, pkg/tools/kubectl_tool.go
=> Fixes for Windows

gollm/azopenai.go
fix the response content validation error
=> azopenai: fix the response content validation error

README.md
1. Fix the --quite argument
2. Fix small typos
=> Docs(readme): fix the --quite argument

gollm/openai.go
Need testing with OpenAI api key. 
This should work without any problems.
Error message:
Edit: I don't have an openai key. If anyone can test the command I'll be grateful
=> feat: implement ListModels function to retrieve model IDs from OpenAI

README.md
=> doc: add krew install document

docs/mcp.md
=> User guide for the `mcp-server` mode

install.sh
The links in the install.sh script were wrong
=> Updated links in the install.sh script

gollm/factory.go
- Add a method to list registered providers in the registry
- Improve error messages to include available providers when a provider is not registered or LLM_CLIENT is not set
- Add mutex locking to provider creation for thread safety
- Replace commented-out and info-level retry logs with structured, verbosity-controlled logging for retry attempts
=> feat: refactor provider registry for safety and improved diagnostics

README.md
Adds docs about custom tools. Also, `README` is getting very long. Cleaning it up to keep it easy to read.
=> Document custom tools and enhance README

README.md, cmd/main.go, pkg/tools/tools.go
Refs: https://github.com/GoogleCloudPlatform/kubectl-ai/issues/239
=> Add special command for listing available tools

pkg/tools/custom_tool.go
Refs: https://github.com/GoogleCloudPlatform/kubectl-ai/issues/239
=> Pass command args to custom tools

README.md, cmd/main.go, pkg/tools/tools.go
Depends on #247 and #248.
Refs: https://github.com/GoogleCloudPlatform/kubectl-ai/issues/239
=> Support multiple custom tools configs

go.mod, go.sum, gollm/azopenai.go, gollm/go.mod, gollm/go.sum
I am sure that it can be even better, but I don't see any support in the SDK at the moment.
=> Optimize listing models for Azure OpenAI

gollm/ollama.go
Bump to Gemma 3: https://ollama.com/library/gemma3
=> gollm: bump default model for ollama provider

go.mod, go.sum, gollm/go.mod, gollm/go.sum, gollm/grok.go, gollm/openai.go
This PR updates the codebase to adopt the OpenAI v1.0.0 API, ensuring compatibility with the latest SDK changes. It modifies the way chat completion requests are constructed, transitioning from previous message structures to the new `ChatCompletionMessageParamUnion` format. Additionally, stream handling has been updated to correctly process tool calls, aligning the struct field naming conventions with the latest SDK, notably changing `Id` to `ID`. These changes improve the stability and correctness of OpenAI integrations.
- `gollm/openai.go`: Main updates to the completion request format and stream processing.
- `gollm/grok.go`: Transformation of tool call deserialization to use the new message format.
- SDK dependency updated to `github.com/openai/openai-go v1.0.0`.
- **API Version …
=> Update OpenAI and Stream Handling for Compatibility with v1.0.0 API

Taskfile.yml
This pull request introduces a `Taskfile.yml` to streamline development workflows by defining reusable tasks for building, running, testing, and maintaining the project. The `Taskfile.yml` simplifies common operations and provides a clear structure for managing development and CI-related tasks.
Reusing the existing test scripts whenever possible.
**Taskfile Introduction:**
* Added a `Taskfile.yml` with a version specification (`3`) and support for `.env` files for environment variable management.
**Testing and Coverage:**
* Included tasks for running tests (`test`, `test-verbose`) and generating test coverage reports (`test-coverage`).
**Maintenance and Development Workflow:**
* Added tasks for cleaning build artifacts (`clean`), managing dependencies (`deps`, `update-deps`), and running …
=> Created a Taskfile to help with routine tasks.

README.md, install.sh
A few days ago my PR (https://github.com/NixOS/nixpkgs/pull/408030/) to package kubectl-ai for [NixOS](https://nixos.org/) got merged, so i think it would be good to document the install process here too. Also i included a small check for NixOS-systems in the install script.
=> Updated install.sh and README.md to document the installation on NixOS

pkg/agent/conversation.go, pkg/tools/bash_tool.go, pkg/tools/custom_tool.go, pkg/tools/custom_tool_test.go
* Use bash to invoke the custom tool command
* Add command prefix if missing
=> Fixed minor bugs in executing custom tools

.github/workflows/ci-periodic.yaml, k8s-bench/README.md, k8s-bench/main.go
fix: https://github.com/GoogleCloudPlatform/kubectl-ai/issues/348
=> feat: Disable `enable-tool-use-shim` in k8s-bench by default.

k8s-bench/tasks/fix-oomkilled/artifacts/memory-hungry-app.yaml, k8s-bench/tasks/fix-oomkilled/cleanup.sh, k8s-bench/tasks/fix-oomkilled/setup.sh, k8s-bench/tasks/fix-oomkilled/task.yaml, k8s-bench/tasks/fix-oomkilled/verify.sh
```bash
Running verifier for task fix-oomkilled
Running command: /home/prasad89/kubectl-ai/k8s-bench/tasks/fix-oomkilled/verify.sh
deployment.apps/backend-api condition met
pod/backend-api-6b47875476-77blm condition met
pod/backend-api-7dbd954744-zmztb condition met
Pod is running successfully without OOMKilled events
```
=> eval: Added eval for troubleshooting and fixing OOMKilled pod

cmd/mcp_client.go, gollm/gemini.go, gollm/interfaces.go, pkg/mcp/client.go, pkg/mcp/manager.go, pkg/tools/mcp_tool.go
This makes the MCP tool usage much more accurate.
=> mcp support: map schemas from MCP to our schema

gollm/openai.go, gollm/openai_test.go, pkg/mcp/client.go
This PR introduces various improvements in the handling of chat messages, schema validation, function call processing, and model selection for OpenAI integrations. It refines the way content types are processed into chat history, fixes schema normalization to ensure compatibility with OpenAI, and adds robust error handling for function arguments. Additionally, it provides a flexible approach to model selection based on explicit input and configuration, with default fallbacks. Minor updates also enhance the conversion of schema types and MCP schema handling.
- `pkg/mcp/client.go`
- Chat session management in `openAIChatSession`
- Schema validation functions
- Utility functions for model selection and function call conversions
- **Content Processing:**
- `processContentsToHistory` appends …
=> Enhancements to OpenAI Chat Session Handling, Schema Validation, and Model Selection

pkg/tools/kubectl_filter.go, pkg/tools/kubectl_filter_test.go
Fix: #393
Previously, all rollout commands were incorrectly categorized as write operations,
resulting in unnecessary approval prompts for read-only subcommands such as history and status.
This PR introduces dedicated mappings for subcommands like `rollout` :
It can also be applied to commands like:
- auth can-i (read-only, checks permissions)
- auth reconcile (write, updates permission rules)
=> feat: Ensure accurate read/write classification for kubectl sub commands like `kubectl rollout history`

pkg/ui/html/index.html
Simple toggle and browser colorscheme detection
=> feat: UI Darkmode toggle

images/kubectl-ai/Dockerfile
Adding gcloud to kubectl-ai image to support work in #264
=> [WIP] Feat/docker image with gcloud

pkg/agent/conversation.go
Resolves https://github.com/GoogleCloudPlatform/kubectl-ai/issues/439
=> feat: implement exit and quit commands to gracefully terminate the conversation

.github/workflows/ci-periodic.yaml
Simplifying the eval run to investigate https://github.com/GoogleCloudPlatform/kubectl-ai/issues/488
=> ci: make periodic eval run sequential

docs/bedrock.md, docs/mcp-client.md, docs/mcp-server.md, docs/tools.md
- Add spacing and clarify the list of currently supported Claude models in Bedrock documentation
- Expand architecture and execution flow details in MCP client documentation, including a fixed sequence for system components
- Add sample workflows for advanced incident response and compliance automation scenarios
- Document configuration examples and architecture in MCP server guide, including tool discovery and routing details
- Improve headings, add clarification steps, and enhance formatting in custom tools documentation
=> docs: enhance and clarify MCP and Bedrock documentation

pkg/ui/html/index.html
This PR adds support for multiline input in the web UI, allowing users to enter newlines in the prompt which fixes #487. It also improves the scrollbar styling for a better user experience.
Key changes:
- Replaced the `<input>` field with a `<textarea>` to allow for multiline text.
- Implemented an `onKeyDown` event handler to submit the form on "Enter" and insert a newline on "Shift+Enter".
- Added JavaScript to automatically resize the textarea based on its content.
- Updated the CSS to provide a more modern, subtle scrollbar that only appears when necessary.
- Applied the new scrollbar style to both the main chat area and the new textarea for consistency.
_Dark mode preview_
_Light mode preview_
=> feat(web): Add support for multiline input

.github/workflows/release.yaml
Accidentally installed wrong mockgen 🙃
=> fix: go releaser

pkg/agent/conversation.go, pkg/agent/systemprompt_template_default.txt
The ensures that if kubectl-ai is being run in an unattended mode, it doesn't steer the LLM to ask for clarifications/inputs.
=> Made the system prompt to be human interaction aware

gollm/factory.go, k8s-bench/tasks/list-images-for-pods/artifacts/Makefile, k8s-bench/tasks/list-images-for-pods/artifacts/manifest.yaml, k8s-bench/tasks/list-images-for-pods/task.yaml
* Updates list-images-for-pods to no longer use bitnami charts
Due to bitnami removing all their free charts from docker hub, setup script fails every time; https://github.com/bitnami/charts/issues/35164
=> feat: fix list-images-for-pods issues
